name: CMake Build Matrix

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux"
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: "macOS"
            os: macos-latest
            cc: clang
            cxx: clang++
          - name: "Windows"
            os: windows-latest
            cc: cl
            cxx: cl
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            arch: win64_msvc2017_64

    steps:
      - uses: actions/checkout@v1

      - name: Install CMake
        uses: symbitic/install-cmake@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: '${{ matrix.config.arch }}'
          version: '5.14.2'
          modules: 'qtcharts'

      - name: Configure build environment on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          call "${{ matrix.config.environment_script }}"
        shell: cmd

      - name: Configure
        run: cmake --config Debug -S . -B build -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -G Ninja

      - name: Build
        run: cmake --build build --config Debug -j 4

      - name: Test
        run: cmake --build build --config Debug --target test
