name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Linux"
            os: ubuntu-latest
          - name: "macOS"
            os: macos-latest
          - name: "Windows"
            os: windows-latest
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            arch: win64_mingw73

    steps:
      - uses: actions/checkout@v1

      - name: Install CMake
        uses: symbitic/install-cmake@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: "${{ matrix.config.arch }}"
          version: "5.14.2"
          modules: "qtcharts"

      - name: Install rpm
        if: startsWith(matrix.config.os, 'ubuntu')
        run: sudo apt-get install rpm

      - name: Configure build environment on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          call "${{ matrix.config.environment_script }}"
        shell: cmd

      - name: Configure
        run: cmake --config Release -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 4

      - name: Package
        run: cpack
        working-directory: build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/SqlTest-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
